apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: k8stest:v1
    volumeMounts:
    - mountPath: /app
      name: test-volume
    ports:
    - containerPort: 3000
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: ${DIR}
---
kind: Service
apiVersion: v1
metadata:
  name: test-service
spec:
  selector:
    app: test
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer